In [109]:
import pandas as pd
import numpy as np

In [36]:
train = pd.read_csv('linear_train.txt', header=-1)

In [4]:
linear_and_example = pd.read_csv('linear_ans_example.txt')

In [5]:
test = pd.read_csv('linear_test.txt', header=-1)

In [37]:
train.head()

          0  1
0  Аалтонен  1
1       Аар  0
2     Аарон  0
3     ААРОН  0
4    Аарона  0

In [7]:
train[train[1] == 1].shape

(10638, 2)

In [8]:
train[train[1] == 0].shape

(90770, 2)

Выделим признаки:

1. Начинается с заглавной буквы
2. Длина слова (?)
3. есть ли несколько подряд гласных (>= 3)
4. есть ли несколько подряд согласных (>=3)

In [165]:
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.metrics import roc_auc_score, make_scorer

from sklearn.svm import SVC, LinearSVC

from sklearn.model_selection import cross_val_score

from sklearn.linear_model import LogisticRegression

from sklearn.feature_extraction.text import TfidfTransformer

from sklearn.pipeline import make_pipeline

from sklearn.svm import SVC, LinearSVC

In [234]:
count_vect = CountVectorizer(ngram_range=(2, 3), analyzer='char_wb')

In [192]:
test.index += train.shape[0]

In [194]:
train

                 0  1
0         Аалтонен  1
1              Аар  0
2            Аарон  0
3            ААРОН  0
4           Аарона  0
5           Аарона  1
6           Аароне  0
7          Ааронов  0
8           Аахена  0
9          Абабков  1
10          абажур  0
11        абажуром  0
12         абажуры  0
13         Абажуры  0
14            абак  0
15         абаками  0
16         Абакана  0
17          абаком  0
18        Абакумов  1
19        Абалкина  1
20      Абатуровым  1
21          Абашев  1
22        Абашидзе  1
23        Абашкина  1
24           Аббас  1
25           АББАС  1
26          Аббаса  1
27         Аббасов  1
28        аббатами  0
29          аббате  0
...            ... ..
101378      ящериц  0
101379     ящерица  0
101380    ящерицам  0
101381     ящерице  0
101382     ящерицы  0
101383      ящерка  0
101384      ящерок  0
101385      ящером  0
101386       ящеру  0
101387        ящик  0
101388        ЯЩИК  0
101389        ящик  1
101390       Ящика  0
101391       ЯЩИКА  0
101392      ЯЩИКАМ  0
101393      ящиках  0
101394       ЯЩИКИ  0
101395      ЯЩИКОВ  0
101396      ящиком  0
101397      Ящиком  0
101398     ящичках  0
101399     ящичков  0
101400      ящичку  0
101401        ящур  0
101402       ящура  0
101403       Ёлкин  1
101404       ёлкой  0
101405        ёлок  0
101406     ёлочкой  0
101407     ёмкость  0

[101408 rows x 2 columns]

In [196]:
test

                0
101408     ﻿Аалто
101409        ААР
101410       Аара
101411       Ааре
101412      Аарон
101413     Аароне
101414    Ааронов
101415    Аароном
101416    Аароном
101417     Аарону
101418     Аарону
101419      Аахен
101420     Аахене
101421    Аахеном
101422         АБ
101423     Абадан
101424    Абадане
101425   Абаданом
101426      Абаев
101427     Абаева
101428    Абаевым
101429     Абажур
101430    абажура
101431  абажурами
101432   абажурах
101433    абажуре
101434   абажуров
101435    абажуру
101436       Абак
101437       АБАК
...           ...
290298     ящичка
290299    ящичкам
290300   ящичками
290301     ящичке
290302     ящички
290303     Ящички
290304    ящичком
290305      ящуре
290306     ящуром
290307         ёж
290308         Ёж
290309       ёжик
290310      ёжика
290311      ёжике
290312     ёжиком
290313       ёлка
290314     ёлками
290315       ёлке
290316       ёлки
290317       Ёлки
290318       ёлку
290319     ёлочек
290320     ёлочка
290321     ёлочки
290322   ёмкостей
290323    ёмкости
290324    Ёмкости
290325    Ёмкость
290326   ёмкостью
290327   ёмкостях

[188920 rows x 1 columns]

In [202]:
all_data = pd.concat([train[0], test[0]])

In [235]:
sparse_matrix = count_vect.fit_transform(all_data)

101408

In [236]:
train_sp_matrix = sparse_matrix[:101408, :]
test_sp_matrix = sparse_matrix[101408:, :]

In [237]:
model = LogisticRegression()

In [238]:
model.fit(train_sp_matrix, train[1])

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [239]:
prediction = model.predict_proba(test_sp_matrix)[:, 1]

In [240]:
linear_and_example['Answer'] = prediction

In [241]:
sum(prediction)

19755.939667556679

In [242]:
linear_and_example

            Id    Answer
0            0  0.427587
1            1  0.203625
2            2  0.213745
3            3  0.135413
4            4  0.224977
5            5  0.134647
6            6  0.258841
7            7  0.197287
8            8  0.197287
9            9  0.223357
10          10  0.223357
11          11  0.144749
12          12  0.074376
13          13  0.095457
14          14  0.184042
15          15  0.158873
16          16  0.057500
17          17  0.147666
18          18  0.828656
19          19  0.953870
20          20  0.987041
21          21  0.022095
22          22  0.027194
23          23  0.004458
24          24  0.001920
25          25  0.018712
26          26  0.024071
27          27  0.023052
28          28  0.175735
29          29  0.175735
...        ...       ...
188890  188890  0.015590
188891  188891  0.002414
188892  188892  0.001583
188893  188893  0.002975
188894  188894  0.013805
188895  188895  0.013805
188896  188896  0.017507
188897  188897  0.027755
188898  188898  0.048634
188899  188899  0.117849
188900  188900  0.117849
188901  188901  0.063907
188902  188902  0.025841
188903  188903  0.010139
188904  188904  0.026067
188905  188905  0.046454
188906  188906  0.004854
188907  188907  0.017836
188908  188908  0.090383
188909  188909  0.090383
188910  188910  0.029162
188911  188911  0.030238
188912  188912  0.051072
188913  188913  0.045412
188914  188914  0.006779
188915  188915  0.011983
188916  188916  0.011983
188917  188917  0.018004
188918  188918  0.002278
188919  188919  0.000366

[188920 rows x 2 columns]

In [243]:
linear_and_example.to_csv("linear_and_example.tsv", sep=',', index=False)